# Generated by Django 2.2 on 2024-02-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='technician',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
    ]
