# Generated by Django 2.2 on 2024-02-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0002_auto_20240216_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
