# Generated by Django 2.2 on 2024-04-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0004_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ETS_app.serviceCategory')),
            ],
        ),
    ]
