# Generated by Django 2.2 on 2024-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0005_service_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
