# Generated by Django 2.2 on 2024-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0006_servicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
