# Generated by Django 2.2 on 2024-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0007_technician_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='b_image',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='f_image',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='technician',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
