# Generated by Django 2.2 on 2024-04-20 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0008_auto_20240419_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(default=None)),
                ('occupation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ETS_app.M_Occupation')),
            ],
        ),
    ]
