# Generated by Django 2.2 on 2024-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0009_m_occupation_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
    ]
