# Generated by Django 2.2 on 2024-05-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0010_service_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
