# Generated by Django 2.2 on 2024-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0012_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
