# Generated by Django 2.2 on 2024-05-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0013_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='image',
        ),
    ]
