# Generated by Django 2.2 on 2024-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0016_remove_servicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
