# Generated by Django 2.2 on 2024-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0017_servicecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('t_email', models.EmailField(max_length=254)),
                ('t_phone', models.CharField(max_length=20)),
                ('c_address', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('t_status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
