# Generated by Django 2.2 on 2024-05-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
