# Generated by Django 2.2 on 2024-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0020_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='f_status',
            field=models.CharField(default='on-going', max_length=12),
        ),
    ]
