# Generated by Django 2.2 on 2024-05-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0021_order_f_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='f_status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
