# Generated by Django 2.2 on 2024-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETS_app', '0022_auto_20240513_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
